name: Bazel - Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: bazel build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install bazel
        run: |
          brew install bazelisk
      - name: Build
        run: |
          bazel build //MinimalBazelFrameworkDemo:MinimalBazelFrameworkDemoApp
